---
deployment:
  tasks:
    - export DEPLOYPATH=/home/c2423708c/public_html
    - /bin/cp -r . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/alive.php $DEPLOYPATH/alive.html $DEPLOYPATH/debug-site.php
