<?php
/**
 * GamTech wp-config.php Recovery Script
 * 
 * If your site shows a 500 error, upload this file to your site root
 * and visit: https://gamtech-electronic.com/setup-config.php
 * 
 * This will create wp-config.php from the local Docker config template.
 * DELETE this file after running it!
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$wp_config_path = __DIR__ . '/wp-config.php';

// If wp-config.php already exists, show status
if (file_exists($wp_config_path)) {
    echo "<h2>wp-config.php already exists</h2>";
    echo "<p>No action needed. Delete this file (setup-config.php) from your server.</p>";
    echo "<p><a href='/'>Go to homepage</a></p>";
    exit;
}

// Create wp-config.php with production-ready template
$config = '<?php
/**
 * GamTech Electronics — wp-config.php
 * Auto-generated by setup-config.php recovery script
 */

// ** Database settings — UPDATE THESE with your cPanel database credentials ** //
define( \'DB_NAME\',     \'c2423708c_gamtech\' );
define( \'DB_USER\',     \'c2423708c_gamtech\' );
define( \'DB_PASSWORD\', \'CHANGE_ME\' );
define( \'DB_HOST\',     \'localhost\' );
define( \'DB_CHARSET\',  \'utf8mb4\' );
define( \'DB_COLLATE\',  \'\' );

// ** Authentication keys and salts ** //
define( \'AUTH_KEY\',         \'gmT!ch@2026#k1 secure-key-1\' );
define( \'SECURE_AUTH_KEY\',  \'gmT!ch@2026#k2 secure-key-2\' );
define( \'LOGGED_IN_KEY\',    \'gmT!ch@2026#k3 secure-key-3\' );
define( \'NONCE_KEY\',        \'gmT!ch@2026#k4 secure-key-4\' );
define( \'AUTH_SALT\',        \'gmT!ch@2026#s1 secure-salt-1\' );
define( \'SECURE_AUTH_SALT\', \'gmT!ch@2026#s2 secure-salt-2\' );
define( \'LOGGED_IN_SALT\',   \'gmT!ch@2026#s3 secure-salt-3\' );
define( \'NONCE_SALT\',       \'gmT!ch@2026#s4 secure-salt-4\' );

$table_prefix = \'wp_\';

// ** Debug settings ** //
define( \'WP_DEBUG\',         false );
define( \'WP_DEBUG_LOG\',     false );
define( \'WP_DEBUG_DISPLAY\', false );

// ** Performance ** //
define( \'WP_MEMORY_LIMIT\', \'256M\' );
define( \'WP_MAX_MEMORY_LIMIT\', \'512M\' );
define( \'AUTOMATIC_UPDATER_DISABLED\', true );

/* That\'s all, stop editing! Happy publishing. */

if ( ! defined( \'ABSPATH\' ) ) {
    define( \'ABSPATH\', __DIR__ . \'/\' );
}

require_once ABSPATH . \'wp-settings.php\';
';

if (file_put_contents($wp_config_path, $config)) {
    echo "<h2>wp-config.php created successfully!</h2>";
    echo "<p><strong>IMPORTANT:</strong> Edit wp-config.php on your server and update:</p>";
    echo "<ul>";
    echo "<li><code>DB_PASSWORD</code> — set your actual MySQL password</li>";
    echo "<li><code>DB_NAME</code> — confirm your database name</li>";
    echo "</ul>";
    echo "<p>Then <strong>DELETE</strong> this setup-config.php file from your server.</p>";
    echo "<p><a href='/'>Go to homepage</a></p>";
} else {
    echo "<h2>Error: Could not create wp-config.php</h2>";
    echo "<p>Check file permissions on your server.</p>";
}
